@"
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: olaff33/mi-web:2.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker build -t $IMAGE_NAME:latest .

    - name: Test Docker image
      run: |
        docker run --rm $IMAGE_NAME:${{ github.sha }} echo "✅ Container test passed"

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest
        echo "✅ Image pushed to Docker Hub"

    - name: Trigger ArgoCD Sync
      if: github.event_name == 'push'
      run: |
        echo "🚀 ArgoCD will auto-sync with the new image"
"@ | Out-File -FilePath ".github/workflows/ci-cd.yaml" -Encoding UTF8