---
# 1. CONFIGMAP básico
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  environment: "development"
  app-name: "Mi App Simple"
---
# 2. DEPLOYMENT con imagen de Docker Hub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: app
        image: olaff33/mi-app:2.0
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: environment
        - name: APP_NAME  
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app-name
---
# 3. SERVICE básico
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app
  ports:
  - port: 80
    targetPort: 80
---
# 4. INGRESS simple
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mi-app-service
            port:
              number: 80
