apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
  namespace: mi-namespace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: mi-app-html
