apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-urgente
  labels:
    app: app-urgente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-urgente
  template:
    metadata:
      labels:
        app: app-urgente
    spec:
      containers:
      - name: app
        image: nginx:alpine  # Imagen oficial que SIEMPRE funciona
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
