apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
  namespace: mi-namespace
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: nginx
        image: olaff33/mi-web:2.0
        ports:
        - containerPort: 80









