apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
  namespace: mi-app-production
  labels:
    app: mi-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  selector:
    app: mi-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
