@"
apiVersion: v1
kind: Service
metadata:
  name: mi-app
spec:
  selector:
    app: mi-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
"@ | Out-File -FilePath "k8s/service.yaml" -Encoding UTF8